=== ronarae/ads/A4_ProjectPlanning/src/main/resources/pps.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="projectPlanning">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="projects" minOccurs="0"/>
                <xs:element ref="employees" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="year" type="xs:integer" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="projects">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="project" type="ProjectType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="employees">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" type="EmployeeType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="ProjectType">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="startDate" type="xs:date"/>
            <xs:element name="endDate" type="xs:date"/>
            <xs:element name="commitments" type="CommitmentListType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="code" type="xs:NCName" use="required"/>
    </xs:complexType>

    <xs:complexType name="CommitmentListType">
        <xs:sequence>
            <xs:element name="hoursPerDay" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                      <xs:extension base="xs:integer">
                        <xs:attribute name="employee" type="xs:integer"/>
                      </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="EmployeeType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="hourlyWage" type="xs:string"/>
            <xs:element name="managedProjects" type="ProjectListType" minOccurs="0"/>
            <xs:element name="allocatedProjects" type="ProjectListType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="number" type="xs:integer" use="required"/>
    </xs:complexType>


    <xs:complexType name="ProjectListType">
        <xs:sequence>
            <xs:element name="project" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="code" type="xs:NCName" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== ronarae/ads/A4_ProjectPlanning/src/main/resources/HvA2011_e1_p1.xml
<?xml version="1.0" ?>
<projectPlanning xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="pps.xsd" 
	year="2011">
  <projects>
    <project code="P100618">
      <title>Workspace rearrangement - BPH-08</title>
      <startDate>2011-02-10</startDate>
      <endDate>2011-05-06</endDate>
      <commitments>
        <hoursPerDay employee="100324">1</hoursPerDay>
      </commitments>
    </project>
  </projects>
  <employees>
    <employee number="100324">
      <name>Carl Y. SILVA</name>
      <hourlyWage>67</hourlyWage>
      <managedProjects>
        <project code="P100618"></project>
      </managedProjects>
      <allocatedProjects>
        <project code="P100618"></project>
      </allocatedProjects>
    </employee>
  </employees>
</projectPlanning>

=== ronarae/ads/A4_ProjectPlanning/src/main/resources/HvA2014_e5_p1.xml
<?xml version="1.0" ?>
<projectPlanning xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="pps.xsd" 
	year="2014">
  <projects>
    <project code="P100438">
      <title>Workspace rearrangement - SCP-08</title>
      <startDate>2014-03-12</startDate>
      <endDate>2014-04-01</endDate>
      <commitments>
        <hoursPerDay employee="100304">3</hoursPerDay>
        <hoursPerDay employee="100293">1</hoursPerDay>
        <hoursPerDay employee="100297">6</hoursPerDay>
        <hoursPerDay employee="100303">1</hoursPerDay>
        <hoursPerDay employee="100286">1</hoursPerDay>
      </commitments>
    </project>
  </projects>
  <employees>
    <employee number="100286">
      <name>Samuel G. PEREZ</name>
      <hourlyWage>25</hourlyWage>
      <managedProjects>
        <project code="P100438"></project>
      </managedProjects>
      <allocatedProjects>
        <project code="P100438"></project>
      </allocatedProjects>
    </employee>
    <employee number="100293">
      <name>Virginia X. TORRES</name>
      <hourlyWage>54</hourlyWage>
      <allocatedProjects>
        <project code="P100438"></project>
      </allocatedProjects>
    </employee>
    <employee number="100297">
      <name>Carolyn D. BROWN</name>
      <hourlyWage>68</hourlyWage>
      <allocatedProjects>
        <project code="P100438"></project>
      </allocatedProjects>
    </employee>
    <employee number="100303">
      <name>Heather Z. HART</name>
      <hourlyWage>66</hourlyWage>
      <allocatedProjects>
        <project code="P100438"></project>
      </allocatedProjects>
    </employee>
    <employee number="100304">
      <name>Jose U. KING</name>
      <hourlyWage>54</hourlyWage>
      <allocatedProjects>
        <project code="P100438"></project>
      </allocatedProjects>
    </employee>
  </employees>
</projectPlanning>

=== ronarae/ads/A4_ProjectPlanning/target/classes/resources/HvA2012_e2_p2.xml
<?xml version="1.0" ?>
<projectPlanning xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="pps.xsd" 
	year="2012">
  <projects>
    <project code="P100029">
      <title>Virtual workplaces - LWB-09</title>
      <startDate>2012-06-19</startDate>
      <endDate>2012-11-07</endDate>
      <commitments>
        <hoursPerDay employee="100312">1</hoursPerDay>
        <hoursPerDay employee="100317">5</hoursPerDay>
      </commitments>
    </project>
    <project code="P100302">
      <title>Floor insulation - IWO-02</title>
      <startDate>2012-01-31</startDate>
      <endDate>2012-05-04</endDate>
      <commitments>
        <hoursPerDay employee="100312">5</hoursPerDay>
        <hoursPerDay employee="100317">1</hoursPerDay>
      </commitments>
    </project>
  </projects>
  <employees>
    <employee number="100312">
      <name>Peter G. RAY</name>
      <hourlyWage>35</hourlyWage>
      <managedProjects>
        <project code="P100029"></project>
      </managedProjects>
      <allocatedProjects>
        <project code="P100029"></project>
        <project code="P100302"></project>
      </allocatedProjects>
    </employee>
    <employee number="100317">
      <name>Joan H. NGUYEN</name>
      <hourlyWage>20</hourlyWage>
      <managedProjects>
        <project code="P100302"></project>
      </managedProjects>
      <allocatedProjects>
        <project code="P100029"></project>
        <project code="P100302"></project>
      </allocatedProjects>
    </employee>
  </employees>
</projectPlanning>

=== ronarae/ads/A4_ProjectPlanning/src/main/resources/HvA2015_e5_p5.xml
<?xml version="1.0" ?>
<projectPlanning xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="pps.xsd" 
	year="2015">
  <projects>
    <project code="P100241">
      <title>Toilets refurbishment - CON-01</title>
      <startDate>2015-04-01</startDate>
      <endDate>2015-06-04</endDate>
      <commitments>
        <hoursPerDay employee="100257">1</hoursPerDay>
        <hoursPerDay employee="100272">4</hoursPerDay>
        <hoursPerDay employee="100263">1</hoursPerDay>
        <hoursPerDay employee="100278">8</hoursPerDay>
        <hoursPerDay employee="100264">3</hoursPerDay>
      </commitments>
    </project>
    <project code="P100575">
      <title>Floor insulation - BPH-05</title>
      <startDate>2015-05-01</startDate>
      <endDate>2015-09-11</endDate>
      <commitments>
        <hoursPerDay employee="100257">1</hoursPerDay>
        <hoursPerDay employee="100272">1</hoursPerDay>
        <hoursPerDay employee="100263">8</hoursPerDay>
        <hoursPerDay employee="100278">1</hoursPerDay>
        <hoursPerDay employee="100264">7</hoursPerDay>
      </commitments>
    </project>
    <project code="P100664">
      <title>Floor insulation - WBH-04</title>
      <startDate>2015-02-02</startDate>
      <endDate>2015-03-31</endDate>
      <commitments>
        <hoursPerDay employee="100257">1</hoursPerDay>
        <hoursPerDay employee="100272">2</hoursPerDay>
        <hoursPerDay employee="100263">8</hoursPerDay>
        <hoursPerDay employee="100264">8</hoursPerDay>
      </commitments>
    </project>
    <project code="P100735">
      <title>Surveillance cameras installation - MLH-05</title>
      <startDate>2015-03-02</startDate>
      <endDate>2015-03-26</endDate>
      <commitments>
        <hoursPerDay employee="100257">1</hoursPerDay>
        <hoursPerDay employee="100272">2</hoursPerDay>
        <hoursPerDay employee="100263">2</hoursPerDay>
        <hoursPerDay employee="100278">1</hoursPerDay>
        <hoursPerDay employee="100264">6</hoursPerDay>
      </commitments>
    </project>
    <project code="P100790">
      <title>Workspace rearrangement - MLH-00</title>
      <startDate>2015-01-21</startDate>
      <endDate>2015-03-26</endDate>
      <commitments>
        <hoursPerDay employee="100272">4</hoursPerDay>
        <hoursPerDay employee="100263">1</hoursPerDay>
      </commitments>
    </project>
  </projects>
  <employees>
    <employee number="100257">
      <name>Sharon V. BUTLER</name>
      <hourlyWage>71</hourlyWage>
      <managedProjects>
        <project code="P100241"></project>
        <project code="P100664"></project>
      </managedProjects>
      <allocatedProjects>
        <project code="P100735"></project>
        <project code="P100241"></project>
        <project code="P100664"></project>
        <project code="P100575"></project>
      </allocatedProjects>
    </employee>
    <employee number="100263">
      <name>Helen R. TERRY</name>
      <hourlyWage>33</hourlyWage>
      <managedProjects>
        <project code="P100790"></project>
      </managedProjects>
      <allocatedProjects>
        <project code="P100735"></project>
        <project code="P100241"></project>
        <project code="P100790"></project>
        <project code="P100664"></project>
        <project code="P100575"></project>
      </allocatedProjects>
    </employee>
    <employee number="100264">
      <name>Nicholas M. GIBSON</name>
      <hourlyWage>34</hourlyWage>
      <allocatedProjects>
        <project code="P100735"></project>
        <project code="P100241"></project>
        <project code="P100664"></project>
        <project code="P100575"></project>
      </allocatedProjects>
    </employee>
    <employee number="100272">
      <name>Larry Y. JENSEN</name>
      <hourlyWage>51</hourlyWage>
      <allocatedProjects>
        <project code="P100735"></project>
        <project code="P100241"></project>
        <project code="P100790"></project>
        <project code="P100664"></project>
        <project code="P100575"></project>
      </allocatedProjects>
    </employee>
    <employee number="100278">
      <name>Brandon U. PAYNE</name>
      <hourlyWage>63</hourlyWage>
      <managedProjects>
        <project code="P100735"></project>
        <project code="P100575"></project>
      </managedProjects>
      <allocatedProjects>
        <project code="P100735"></project>
        <project code="P100241"></project>
        <project code="P100575"></project>
      </allocatedProjects>
    </employee>
  </employees>
</projectPlanning>
